### PR TITLE
Operator mapping - code cleaning

### LINKED ISSUE #232: Operator Mapping Modal Copy needs an update
Screen Shot 2022-10-03 at 9 32 55 AM

### LINKED ISSUE #255: Etherscan link incorrect for operator registration tx
After operator registration the link is: https://etherscan.io/tx/[object%20Object]

### PR DESCRIPTION
**Pull request by michalsmiarowski**
Closes #232 (64677b39e1b6c5234354bcdb5adb933bf3d191bf)
Closes #255 (ae4231d832c00e4cc353d633c1189e4e18ef0382)

# Operator mapping code cleaning

### Main changes:
- rearrange the operator mapping related data in redux store
- adds operator and staking provider addresses as props to the Operator Mapping related modals and `OperatorAddressMappingCard`
- removes unnecessary `shouldDisplayMapOperatorToStakingProviderModal` effect 
- fix some of the review comments from https://github.com/threshold-network/token-dashboard/pull/199
- fix a bug that caused the `MapOperatorToStakingProvider` modal to not be displayed when we changed accounts in MetaMask
- update text in operator mapping modal (Closes: #232)

TODO in the future:
- [ ] display Operator Mapping Card when the operator is mapped - https://github.com/threshold-network/token-dashboard/issues/259
- [ ] display Operator Mapping Card and the modals related to it after submitting a stake (without the need to refresh)

# Change details

### rearrange the operator mapping related data in redux store

Previously we keep the data needed to operator mapping in the redux store in this format:

(1) `rolesOf` property in `connected-account` slice:

```
{
address: string,
  rolesOf: {
    owner: string,
    authorizer: string,
    beneficiary: string, 
}
```

This indicated if the currently logged account is used as a staking provider in other stakes. We fetched the data from the contract.

(2) `mappedOperator` property in `staking-applications` slice:
```
{
  tbtc: {
    parameter: (...),
    stakingProviders: (...),
    mappedOperator: {
      isInitialFetchDone: boolean,
      isFetching: boolean,
      error: string,
      data: string,
  },
  randomBeacon: {
    parameter: (...),
    stakingProviders: (...),
    mappedOperator: {
      isInitialFetchDone: boolean,
      isFetching: boolean,
      error: string,
      data: string,
  }
}
```

This stored the data related to currently logged staking provider and it's mapped operator for each application. This could wrongly indicate that the data is more related to the staking app itself (since it was in the `staking-application` slice) when in reality it was more related to currently connected account.

At first the idea was to not store this data in redux store at all, but unfrotunately this didn't went as smooth as I thogught and I think we must store them mainly to properly display `OperatorAddressMappingCard` in the staking page for all staking providers that don't have the operator mapped. I've encoutered problems with implementing it without using the store when the staking provider !=== owner.

This is why i decided to go back to keeping the data in the redux store (you can see all this in the commit history) but in better (and i think simpler) form.

Right now we will store this data in `account` slice and we ditched the whole `rolesOf` property which was object, to just `isStakingProvider` which is boolean value. After the changes the `connected-account` is renamed to `account` and looks like this:

```
{
  address: string,
  isStakingProvider: boolean,
  operatorMapping: {
    data: {
      tbtc: string,
      randomBeacon: string,
    },
    isFetching: boolean,
    isInitialFetchDone: boolean,
  },
}
```

### adds operator and staking provider addresses as props to the Operator Mapping related modals and `OperatorAddressMappingCard`

For these components we are adding a props that contains operator address and staking provider address:
- `OperatorAddressMappingCard`
- `MapOperatorToStakingProviderModal`
- `MapOperatorToStakingProviderSuccessModal`
- `MapOperatorToStakingProviderConfirmationModal`
- `MapOperatorToStakingProviderForm`

### removes unnecessary shouldDisplayMapOperatorToStakingProviderModal effect

This effect was unnecessary. Instead of using `predicate` (from redux-toolkit) when calling `displayMapOperatorToStakingProviderModalEffect` we now use `actionCreator` (also from redux-toolkit) to call this effect on `operatorMappingInitialFetchDone` action call which in turn is called by `setStakes` action. This way we are sure we have all needed that in redux store and we can use them in ` displayMapOperatorToStakingProviderModalEffect`

### fix some of the review comments from https://github.com/threshold-network/token-dashboard/pull/199

Most comment were either fixed by itself during the refactor process (the part of code that was commented does no longer exist) and other ones I've tried to fix. For some I've added comments there to start a discussion.

### fix a bug that caused the `MapOperatorToStakingProvider` modal to not be displayed when we changed accounts in MetaMask

We are setting the `isSuccessfullLoginModalClosed` flag to false when resetting the store now, because the reset happend when we change the accounts and the login modal is not displayed in such case. We also set `isMappingOperatorToStakingProviderModalClosed` flag back to false in this case.

**Additional note**: The modal queue was also moved in the store to `modal` prop since it's related to modal. In the furue we are planning to create a real modal queue.

### update text in operator mapping modal 

Update text based on Figma designs in `OperatorAddressMappingCard` component and in `MapOperatorToStakingProviderModal`. For more details see #232

### CODE REVIEW

File: src/components/Modal/MapOperatorToStakingProviderConfirmationModal/index.tsx [hunk 1]
```diff
@@ -60,17 +54,27 @@ const OperatorMappingConfirmation: FC<
...
   const { registerMultipleOperators } =
     useRegisterMultipleOperatorsTransaction()
-  const dispatch = useDispatch()
+  const dispatch = useAppDispatch()
+
+  const isOperatorMappedOnlyInTbtc =
+    !isAddressZero(mappedOperatorTbtc) &&
+    isAddressZero(mappedOperatorRandomBeacon)
 
-  const operatorMappedToStakingProviderHelpers =
```
Comment (georgeweiler) [inline src/components/Modal/MapOperatorToStakingProviderConfirmationModal/index.tsx:70]: why remove this helper hook? seems like it saved some duplicate code. What if we added the tbtc & random beacon addresses as parameters so we don't have to rewrite the logic?

File: src/components/Modal/MapOperatorToStakingProviderModal/MapOperatorToStakingProviderForm.tsx [hunk 2]
```diff
@@ -69,14 +73,14 @@ const MapOperatorToStakingProviderForm = withFormik<
         }
         if (
           isOperatorMappedOnlyInRandomBeacon &&
-          values.operator !== operatorMappedRandomBeacon
+          values.operator !== mappedOperatorRandomBeacon
         ) {
           validationMsg =
             "The operator address doesn't match the one used in tbtc app"
```
Comment (georgeweiler) [inline src/components/Modal/MapOperatorToStakingProviderModal/MapOperatorToStakingProviderForm.tsx:79]: let's use tBTC

File: src/components/Modal/MapOperatorToStakingProviderSuccessModal/index.tsx [hunk 3]
```diff
@@ -37,43 +37,50 @@ const MapOperatorToStakingProviderSuccessBase: FC<
       body={
         <>
           <List spacing="2" mb={"4rem"}>
```
Comment (georgeweiler) [inline src/components/Modal/MapOperatorToStakingProviderSuccessModal/index.tsx:39]: minor suggestion, but can we use `16` instead of `4rem` since we have to touch this file to update the typo below anyway

File: src/components/Modal/MapOperatorToStakingProviderSuccessModal/index.tsx [hunk 4]
```diff
@@ -37,43 +37,50 @@ const MapOperatorToStakingProviderSuccessBase: FC<
...
-                <BodySm>Operator</BodySm>
+                <BodySm>Provider Address</BodySm>
                 <BodySm>
-                  {shortenAddress(transactions[0].application.operator)}
+                  {shortenAddress(transactions[0].application.stakingProvider)}
                 </BodySm>
               </HStack>
             </ListItem>
-            <ListItem key="map_operator_succes_modal__staking_provider">
+            <ListItem key="map_operator_succes_modal__operator">
```
Comment (georgeweiler) [inline src/components/Modal/MapOperatorToStakingProviderSuccessModal/index.tsx:48]: same as above

File: src/components/Modal/MapOperatorToStakingProviderSuccessModal/index.tsx [hunk 5]
```diff
@@ -37,43 +37,50 @@ const MapOperatorToStakingProviderSuccessBase: FC<
...
-              >
-                View{" "}
+          <BodySm align="center" mt={"1"}>
+            {transactions.length === 1 ? (
+              <>
                 <ViewInBlockExplorer
-                  text={text}
-                  id={transaction.txHash}
+                  text="View"
+                  id={`map_operator_transaction_${transactions[0].txHash}`}
```
Comment (georgeweiler) [inline src/components/Modal/MapOperatorToStakingProviderSuccessModal/index.tsx:62]: how does this work? Doesn't the `ViewInBlockExplorer` pass this `id` along as the hash to create the link?

File: src/hooks/staking-applications/useRegisterMultipleOperatorsTransaction.ts [hunk 6]
```diff
@@ -23,25 +29,27 @@ export const useRegisterMultipleOperatorsTransaction = () => {
...
+
         if (
-          !isAddressZero(operatorMappedRandomBeacon) &&
-          !isAddressZero(operatorMappedTbtc)
+          !isAddressZero(mappedOperatorRandomBeacon) &&
+          !isAddressZero(mappedOperatorTbtc)
         )
           throw new Error("Both apps already have mapped operator!")
 
+        const isOperatorMappedOnlyInTbtc =
```
Comment (georgeweiler) [inline src/hooks/staking-applications/useRegisterMultipleOperatorsTransaction.ts:45]: see my comment about about the helper hook that we removed. I think it could be nice to consolidate

File: src/pages/Staking/OperatorAddressMappingCard.tsx [hunk 7]
```diff
@@ -8,19 +8,34 @@ import {
...
 import { LabelSm } from "@threshold-network/components"
+import { FC } from "react"
 import { ModalType } from "../../enums"
-import { useOperatorMappedtoStakingProviderHelpers } from "../../hooks/staking-applications/useOperatorMappedToStakingProviderHelpers"
+// import { useOperatorMappedtoStakingProviderHelpers } from "../../hooks/staking-applications/useOperatorMappedToStakingProviderHelpers"
 import { useModal } from "../../hooks/useModal"
+import { isAddressZero } from "../../web3/utils"
 
-const OperatorAddressMappingCard = () => {
+//TODO: Fix this
```
Comment (georgeweiler) [inline src/pages/Staking/OperatorAddressMappingCard.tsx:17]: Could we leave a better explanation for what's wrong & how we should fix? Or maybe just fix now? tbh I don't see any issues, so maybe this comment can be deleted?

File: src/store/connected-account/connectedAccountSlice.ts [hunk 8]
```diff
@@ -51,21 +106,29 @@ export const connectedAccountSlice = createSlice({
...
     )
   },
 })
 
-startAppListening({
-  actionCreator: setStakes,
-  effect: getRolesOf,
-})
+export const registerConnectedAccountListeners = () => {
+  if (featureFlags.MULTI_APP_STAKING) {
```
Comment (georgeweiler) [inline src/store/connected-account/connectedAccountSlice.ts:117]: maybe we don't need this flag anymore since we launched MAS.

File: src/store/index.ts [hunk 9]
```diff
@@ -53,6 +55,15 @@ const rootReducer: Reducer = (state: RootState, action: AnyAction) => {
         T: { ...state.token.T, balance: 0 },
         TBTC: { ...state.token.TBTC, balance: 0 },
       },
+      // we don't display successful login modal when changin account so we are
+      // setting the isSuccessfullLoginModalClosed flag to true and also
+      // isMappingOperatorToStakingProviderModalClosed flag back to false
+      modal: {
+        modalQueue: {
+          isSuccessfullLoginModalClosed: true,
```
Comment (georgeweiler) [inline src/store/index.ts:63]: small typo should be `isSuccessfulLoginModalClosed`

**Review by georgeweiler — CHANGES_REQUESTED** [review]
Overall the state changes look good! I'm not a fan of the modalQueue as it is implemented right now. I think we should prioritize a real queue so we aren't making specific exceptions in the `closeModal` method.  I think this is non-blocking though because it's a larger update that we can do in a future PR.

I left a few small nits that we should cover before merging

File: src/store/staking-applications/effects.ts [hunk 10]
```diff
@@ -168,114 +170,54 @@ const getKeepStakingAppStakingProvidersData = async (
...
+  if (!modalQueue.isSuccessfullLoginModalClosed) {
+    await listenerApi.condition((action, currentState: RootState) => {
+      return currentState.modal.modalQueue.isSuccessfullLoginModalClosed
+    })
+  }
   const { address } = connectedAccount
-  if (address) {
-    // check if the current connected address is used somewhere as a staking
-    // provider
+  if (address && connectedAccount.operatorMapping.isInitialFetchDone) {
```
Comment (r-czajkowski) [inline src/store/staking-applications/effects.ts:187]: Let's remove this nested if for better readability:
```ts
if(!address || !connectedAccount.operatorMapping.isInitialFetchDone) return

...rest here
```

Comment (r-czajkowski) [inline src/store/staking-applications/effects.ts:187]: Do we need this condition `connectedAccount.operatorMapping.isInitialFetchDone`? We run this effect on `operatorMappingInitialFetchDone` so we can assume it is set to `true`.

File: src/store/staking-applications/effects.ts [hunk 11]
```diff
@@ -168,114 +170,54 @@ const getKeepStakingAppStakingProvidersData = async (
...
   action: AnyAction,
   listenerApi: AppListenerEffectAPI
 ) => {
-  const { connectedAccount } = listenerApi.getState()
+  const {
+    modal: { modalQueue },
+  } = listenerApi.getState()
+  const { connectedAccount, staking } = listenerApi.getState()
+  if (!modalQueue.isSuccessfullLoginModalClosed) {
+    await listenerApi.condition((action, currentState: RootState) => {
```
Comment (r-czajkowski) [inline src/store/staking-applications/effects.ts:182]: Do we need the `RootState` type here? The `listenerApi` has our custom type with our state type so I believe it's unnecessary.

File: src/store/index.ts [hunk 12]
```diff
@@ -17,8 +17,10 @@ import {
...
 import { listenerMiddleware } from "./listener"
-import { connectedAccountSlice } from "./connected-account"
-import { modalQueueSlice } from "./modalQueue"
+import {
+  connectedAccountSlice,
+  registerConnectedAccountListeners,
+} from "./connected-account"
 
 const combinedReducer = combineReducers({
   connectedAccount: connectedAccountSlice.reducer,
```
Comment (r-czajkowski) [inline src/store/index.ts:26]: Can we rename to `account/user/app`?

File: src/store/connected-account/index.ts [hunk 13]
```diff
@@ -1,2 +1 @@
 export * from "./connectedAccountSlice"
```
Comment (r-czajkowski) [inline src/store/connected-account/index.ts:1]: Same as above.

File: src/store/connected-account/effects.ts [hunk 14]
```diff
@@ -1,37 +1,64 @@
...
+      )
+
+      listenerApi.dispatch(
+        setMappedOperator({
+          appName: "randomBeacon",
+          operator: mappedOperators.randomBeacon,
+        })
+      )
+
+      listenerApi.dispatch(operatorMappingInitialFetchDone())
```
Comment (r-czajkowski) [inline src/store/connected-account/effects.ts:54]: I believe this action is unnecessary. We can set a flag to true in `setMappedOperator` slice.

File: src/store/connected-account/effects.ts [hunk 15]
```diff
@@ -1,37 +1,64 @@
...
   listenerApi: AppListenerEffectAPI
 ) => {
   try {
     const { connectedAccount } = listenerApi.getState()
     const { address } = connectedAccount
-
-    if (!address) return
-    listenerApi.unsubscribe()
     const { owner, authorizer, beneficiary } =
       await listenerApi.extra.threshold.staking.rolesOf(address)
```
Comment (r-czajkowski) [inline src/store/connected-account/effects.ts:20]: This effect will be triggered on `setStakes` action so it means we should have available stakes if the user is an owner. We can check if the stake where `stakingprovider === connected account` exists in the `stakes` array. If that stake exists there is no need to make the `rolesOf` request.

File: src/store/connected-account/effects.ts [hunk 16]
```diff
@@ -1,37 +1,64 @@
...
-      isAddressZero(beneficiary)
-    ) {
-      listenerApi.dispatch(mapOperatorToStakingProviderModalClosed())
+
+    const isUsedAsStakingProvider =
+      !isZeroAddress(owner) &&
+      !isZeroAddress(authorizer) &&
+      !isZeroAddress(beneficiary)
+
+    if (isUsedAsStakingProvider) {
```
Comment (r-czajkowski) [inline src/store/connected-account/effects.ts:27]: Can we `if(!isUsedAsStakingProvider) return`? There is a lot of code inside the `if` statement so IMO it will improve readability.

File: src/store/connected-account/connectedAccountSlice.ts [hunk 17]
```diff
@@ -1,27 +1,42 @@
...
   name: "connected-account",
   initialState: {
     address: "",
-    rolesOf: {
-      owner: "",
-      authorizer: "",
-      beneficiary: "",
+    operatorMapping: {
+      data: {
+        isUsedAsStakingProvider: false,
```
Comment (r-czajkowski) [inline src/store/connected-account/connectedAccountSlice.ts:32]: I think we should't keep it in the `operatorMapping` object. It's not only related to the operator mapping it could be useful in other places. So I would keep it outside the `operatorMapping` object.
```
initialState: {
 address: string,
 isStakingProvider: boolean
}
```

File: src/store/connected-account/connectedAccountSlice.ts [hunk 18]
```diff
@@ -31,13 +46,53 @@ export const connectedAccountSlice = createSlice({
...
+      const { isFetching } = action.payload
+      state.operatorMapping.isFetching = isFetching
+    },
+    operatorMappingInitialFetchDone: (
+      state: ConnectedAccountState,
+      action: PayloadAction
+    ) => {
+      state.operatorMapping.isFetching = false
+      state.operatorMapping.isInitialFetchDone = true
+    },
```
Comment (r-czajkowski) [inline src/store/connected-account/connectedAccountSlice.ts:78]: Can't we set the `isInitialFetchDone` and `isFetching` in the `setMappedOperator`?

File: src/store/connected-account/connectedAccountSlice.ts [hunk 19]
```diff
@@ -1,27 +1,42 @@
...
+  operatorMapping: FetchingState<{
+    isUsedAsStakingProvider: boolean
+    mappedOperators: {
+      tbtc: string
+      randomBeacon: string
+    }
+  }>
 }
 
 export const connectedAccountSlice = createSlice({
```
Comment (r-czajkowski) [inline src/store/connected-account/connectedAccountSlice.ts:26]: Let's rename to `account/user/app` as I mentioned somewhere above.

File: src/pages/Staking/index.tsx [hunk 20]
```diff
@@ -47,32 +46,10 @@ const StakingPage: PageComponent = (props) => {
...
-    beneficiary,
-    operatorMappedRandomBeacon,
-    operatorMappedTbtc,
-    isInitialFetchDone,
-    isEmptyOrZeroAddress,
-  ])
+  const {
+    isInitialFetchDone: isOperatorMappingInitialFetchDone,
+    data: { isUsedAsStakingProvider, mappedOperators },
+  } = useSelector((state: RootState) => state.connectedAccount.operatorMapping)
```
Comment (r-czajkowski) [inline src/pages/Staking/index.tsx:52]: Let's use `useAppSelector`.

File: src/pages/Staking/OperatorAddressMappingCard.tsx [hunk 21]
```diff
@@ -8,19 +8,34 @@ import {
   HStack,
 } from "@threshold-network/components"
 import { LabelSm } from "@threshold-network/components"
+import { FC } from "react"
 import { ModalType } from "../../enums"
-import { useOperatorMappedtoStakingProviderHelpers } from "../../hooks/staking-applications/useOperatorMappedToStakingProviderHelpers"
+// import { useOperatorMappedtoStakingProviderHelpers } from "../../hooks/staking-applications/useOperatorMappedToStakingProviderHelpers"
```
Comment (r-czajkowski) [inline src/pages/Staking/OperatorAddressMappingCard.tsx:13]: Unnecessary import ?

File: src/pages/Staking/OperatorAddressMappingCard.tsx [hunk 22]
```diff
@@ -8,19 +8,34 @@ import {
   HStack,
 } from "@threshold-network/components"
 import { LabelSm } from "@threshold-network/components"
```
Comment (r-czajkowski) [inline src/pages/Staking/OperatorAddressMappingCard.tsx:10]: We already import components from `@threshold-network/components` so let's import from @threshold-network/components` only once.

File: src/components/Modal/MapOperatorToStakingProviderSuccessModal/index.tsx [hunk 23]
```diff
@@ -37,43 +37,50 @@ const MapOperatorToStakingProviderSuccessBase: FC<
...
                   type={ExplorerDataType.TRANSACTION}
                 />{" "}
+                transaction on Etherscan
+              </>
+            ) : (
+              <>
+                View{" "}
+                {transactions.map((_, index) => (
+                  <Fragment key={`map_operator_transaction_${index}`}>
```
Comment (r-czajkowski) [inline src/components/Modal/MapOperatorToStakingProviderSuccessModal/index.tsx:71]: We could use `_.txHash` as a key.

**Comment by georgeweiler** [comment]
@michalsmiarowski can you take on https://github.com/threshold-network/token-dashboard/issues/232 in this PR as well? Should be a simple commit.

File: src/store/connected-account/connectedAccountSlice.ts (hunk 18 above)
Comment (michalsmiarowski) [reply src/store/connected-account/connectedAccountSlice.ts:78]: I think in this case we can't because the `operatorMapping` property contains:
- `isUsedAsStakingProvider` boolean value
- `mappedOperators` object
and `isInitialFetchDone` and `isFetching` is associated with the `operatorMapping` object as a whole, and `setMappedOperator` sets only `mappedOperators` and not fully - only for specific app. So we can't say the initial fetch is fully done.

File: src/store/connected-account/effects.ts (hunk 14 above)
Comment (michalsmiarowski) [reply src/store/connected-account/effects.ts:54]: I think it's not possible that way. See https://github.com/threshold-network/token-dashboard/pull/223#discussion_r990523464

File: src/store/connected-account/connectedAccountSlice.ts (hunk 17 above)
Comment (michalsmiarowski) [reply src/store/connected-account/connectedAccountSlice.ts:32]: I think this one is also related to https://github.com/threshold-network/token-dashboard/pull/223#discussion_r990523464

I need to know that `isStakingProvider` is fully fetched (and same with mapped operators). This way I can print the Operator Address Mapping Card (PR for it's refactor here - https://github.com/threshold-network/token-dashboard/pull/261) in Staking Page without if displaying for one sec at the beginning (when `isStakingProvider` is set to `true` and the opreator addresses are still fetching). 

But tbh now when I think of it I think we could just check if the mapping operators are initially fetched and that should also work without any problems 🤔

File: src/store/index.ts (hunk 12 above)
Comment (michalsmiarowski) [reply src/store/index.ts]: Fixed in 47639bf858c8fb04be780e3eed636d8e742526b2

File: src/store/connected-account/index.ts (hunk 13 above)
Comment (michalsmiarowski) [reply src/store/connected-account/index.ts]: Fixed in 47639bf858c8fb04be780e3eed636d8e742526b2

File: src/components/Modal/MapOperatorToStakingProviderSuccessModal/index.tsx [hunk 24]
```diff
@@ -37,43 +37,50 @@ const MapOperatorToStakingProviderSuccessBase: FC<
       body={
         <>
           <List spacing="2" mb={"4rem"}>
-            <ListItem key="map_operator_succes_modal__operator">
+            <ListItem key="map_operator_succes_modal__staking_provider">
```
[the remark this answers is not in the document]
Comment (michalsmiarowski) [reply src/components/Modal/MapOperatorToStakingProviderSuccessModal/index.tsx]: Fixed in 45a5009ea7eb56c44fdb0e2846bb33c11a955c07

File: src/components/Modal/MapOperatorToStakingProviderSuccessModal/index.tsx (hunk 3 above)
Comment (michalsmiarowski) [reply src/components/Modal/MapOperatorToStakingProviderSuccessModal/index.tsx]: Fixed in 0de4912594f5fd6521aa3345b3308a75abcdd607

File: src/components/Modal/MapOperatorToStakingProviderSuccessModal/index.tsx (hunk 5 above)
Comment (michalsmiarowski) [reply src/components/Modal/MapOperatorToStakingProviderSuccessModal/index.tsx]: Great catch! I've mistaken it with a `key` prop 🤦‍♂️ Fixed in ae4231d832c00e4cc353d633c1189e4e18ef0382

File: src/pages/Staking/OperatorAddressMappingCard.tsx (hunk 7 above)
Comment (michalsmiarowski) [reply src/pages/Staking/OperatorAddressMappingCard.tsx]: This was fixed earlier and i forgot to remove the TODO. Removed it in 08e6e157803311e44c512bc77cce4c93fedd31dd

File: src/store/connected-account/connectedAccountSlice.ts (hunk 8 above)
Comment (michalsmiarowski) [reply src/store/connected-account/connectedAccountSlice.ts]: I'll address it in separate PR. Let's keep it for a while after release just in case something breaks after newest changes.

File: src/store/index.ts (hunk 9 above)
Comment (michalsmiarowski) [reply src/store/index.ts]: FIxed in d35e967400e6c49cf6c8b8f23ddb6667fb84f61d

File: src/store/staking-applications/effects.ts (hunk 10 above)
Comment (michalsmiarowski) [reply src/store/staking-applications/effects.ts]: Fixed in 88603134d545e9164e5c2de371435ea44441091d

Comment (michalsmiarowski) [reply src/store/staking-applications/effects.ts]: Fixed in 88603134d545e9164e5c2de371435ea44441091d

File: src/store/staking-applications/effects.ts (hunk 11 above)
Comment (michalsmiarowski) [reply src/store/staking-applications/effects.ts]: Fixed in 530837e2820eff1546685b441fe3dddd7c680b02

File: src/store/connected-account/effects.ts (hunk 15 above)
Comment (michalsmiarowski) [reply src/store/connected-account/effects.ts]: Fixed in d3c637b990b9f530b560e94054ff0dd3261d06f9

I couldn't get the stakes from the state using already created selector because even though the effect is called on `setStakes` action they are not set in state yet. Fortunately all the stakes are transferred via payload so that's how i search i any of the stakes there have `stakingProvider === connected account`.

File: src/store/connected-account/effects.ts (hunk 16 above)
Comment (michalsmiarowski) [reply src/store/connected-account/effects.ts]: Fixed in 45c0b72fa274f3314d3c3bd6e471aa5a49a53475

File: src/store/connected-account/connectedAccountSlice.ts (hunk 19 above)
Comment (michalsmiarowski) [reply src/store/connected-account/connectedAccountSlice.ts]: Fixed in 47639bf858c8fb04be780e3eed636d8e742526b2

File: src/pages/Staking/index.tsx (hunk 20 above)
Comment (michalsmiarowski) [reply src/pages/Staking/index.tsx]: Fixed in 4fd84b4c7f1e0a5910ec6a557540305d823d1789

File: src/pages/Staking/OperatorAddressMappingCard.tsx (hunk 21 above)
Comment (michalsmiarowski) [reply src/pages/Staking/OperatorAddressMappingCard.tsx]: Fixed in 369c9c908018a9448a3c5a543197d6d8e9bba994

File: src/pages/Staking/OperatorAddressMappingCard.tsx (hunk 22 above)
Comment (michalsmiarowski) [reply src/pages/Staking/OperatorAddressMappingCard.tsx]: Fixed in 369c9c908018a9448a3c5a543197d6d8e9bba994

File: src/components/Modal/MapOperatorToStakingProviderSuccessModal/index.tsx (hunk 23 above)
Comment (michalsmiarowski) [reply src/components/Modal/MapOperatorToStakingProviderSuccessModal/index.tsx]: Fixed in cdf31809bb34c6f8ea30553d4a91ec44644c5010

File: src/store/index.ts (hunk 9 above)
[the remark this answers is not in the document]
Comment (michalsmiarowski) [reply src/store/index.ts]: Actually it's not dispatched 🤔 And because of that I'm thinking how to resolve this issue. `resetStoreAction` is aclled only when we change the metamas account while we have the account connected. It is not dispatched when we disconnect and then connect again.

**Comment by michalsmiarowski** [comment]
> @michalsmiarowski can you take on #232 in this PR as well? Should be a simple commit.

Fixed in 64677b39e1b6c5234354bcdb5adb933bf3d191bf

File: src/store/index.ts (hunk 9 above)
[the remark this answers is not in the document]
Comment (r-czajkowski) [reply src/store/index.ts]: It's because the injected connector doesn't emit the `Deactivated` event in `deactivate` function https://github.com/Uniswap/web3-react/blob/v6/packages/injected-connector/src/index.ts#L181-L188 but the WalletConnect connector emits this event see https://github.com/Uniswap/web3-react/blob/v6/packages/walletconnect-connector/src/index.ts#L136. So maybe we could override the `deactivate` in InjectedConnector in this way:
```ts
class CustomInjectedConnector extends InjectedConnector {
  deactivate = (): void => {
    super.deactivate()
    this.emitDeactivate()
  }
}

const injectedConnector = new CustomInjectedConnector({})
```

We probably should do the same for `WalletLinkConnector` in `web3/connectors/coinbaseWallet.ts`.

File: src/store/connected-account/connectedAccountSlice.ts (hunk 17 above)
Comment (r-czajkowski) [reply src/store/connected-account/connectedAccountSlice.ts]: > But tbh now when I think of it I think we could just check if the mapping operators are initially fetched and that should also work without any problems

yeah, I think the same. Also the `isStakingProvider` flag will be `false` by default, so to display operator mapping card we will have a condition like this `isStakingProvider && isInitialFetchDone`.

Comment (r-czajkowski) [reply src/store/connected-account/connectedAccountSlice.ts]: If we move the `isStakingProvider` outside the `operatorMapping` object can we also simplify to:
```
operatorMapping: FetchingState<Record<StakingAppName, string>>
```

I believe the `mappedOperators` is unnecessary because it's inside the `operatorMapping`- `operatorMapping` is clear enough and will be simpler
```
state.operatorMapping.data.tbtc/randomBeacon
vs
state.operatorMapping.data.mappedOperator.tbtc/randomBeacon
```

File: src/store/account/effects.ts [hunk 25]
```diff
@@ -0,0 +1,78 @@
+import { isZeroAddress } from "ethereumjs-util"
```
Comment (r-czajkowski) [inline src/store/account/effects.ts:1]: Let's import from `web3/utils`

File: src/store/account/slice.ts [hunk 26]
```diff
@@ -0,0 +1,131 @@
...
+          tbtc: AddressZero,
+          randomBeacon: AddressZero,
+        },
+      },
+      isFetching: false,
+      isInitialFetchDone: false,
+    },
+  } as AccountState,
+  reducers: {
+    setAccountAddress: (state: AccountState, action: PayloadAction<string>) => {
```
Comment (r-czajkowski) [inline src/store/account/slice.ts:43]: maybe `walletConnected`?

**Review by r-czajkowski — CHANGES_REQUESTED** [review]

File: src/store/account/slice.ts [hunk 27]
```diff
@@ -0,0 +1,131 @@
...
+      state.operatorMapping.data.mappedOperators[appName] = operator
+    },
+  },
+  extraReducers: (builder) => {
+    builder.addMatcher(
+      (action: AnyAction) =>
+        action.type.match(providerStakedForStakingProvider),
+      (state, action: ReturnType<typeof providerStaked>) => {
+        const { owner, beneficiary, authorizer, stakingProvider } =
+          action.payload
```
Comment (r-czajkowski) [inline src/store/account/slice.ts:101]: Let's just `const { stakingProvider } = action.payload`

**Review by r-czajkowski — CHANGES_REQUESTED** [review]

File: src/components/Modal/MapOperatorToStakingProviderModal/MapOperatorToStakingProviderForm.tsx [hunk 28]
```diff
@@ -69,17 +73,17 @@ const MapOperatorToStakingProviderForm = withFormik<
         }
         if (
           isOperatorMappedOnlyInRandomBeacon &&
-          values.operator !== operatorMappedRandomBeacon
+          values.operator !== mappedOperatorRandomBeacon
```
[the remark this answers is not in the document]
Comment (michalsmiarowski) [reply src/components/Modal/MapOperatorToStakingProviderModal/MapOperatorToStakingProviderForm.tsx]: Fixed in 7ed1d17e9e0707d79ad3b49c2ef80816c2c48092

File: src/components/Modal/MapOperatorToStakingProviderModal/MapOperatorToStakingProviderForm.tsx [hunk 29]
```diff
@@ -45,15 +46,18 @@ const MapOperatorToStakingProviderForm = withFormik<
...
+    const isOperatorMappedOnlyInTbtc =
+      !isAddressZero(mappedOperatorTbtc) &&
+      isAddressZero(mappedOperatorRandomBeacon)
+
+    const isOperatorMappedOnlyInRandomBeacon =
+      isAddressZero(mappedOperatorTbtc) &&
+      !isAddressZero(mappedOperatorRandomBeacon)
     const errors: FormikErrors<MapOperatorToStakingProviderFormValues> = {}
 
     errors.operator = validateETHAddress(values.operator)
```
[the remark this answers is not in the document]
Comment (michalsmiarowski) [reply src/components/Modal/MapOperatorToStakingProviderModal/MapOperatorToStakingProviderForm.tsx:102]: Fixed in 7ed1d17e9e0707d79ad3b49c2ef80816c2c48092

File: src/components/Modal/MapOperatorToStakingProviderSuccessModal/index.tsx [hunk 30]
```diff
@@ -36,44 +29,51 @@ const MapOperatorToStakingProviderSuccessBase: FC<
       subTitle="You successfully mapped your Operator Address."
       body={
         <>
-          <List spacing="2" mb={"4rem"}>
-            <ListItem key="map_operator_succes_modal__operator">
+          <List spacing="2" mb={"16"}>
+            <ListItem key="map_operator_success_modal__staking_provider">
```
[the remark this answers is not in the document]
Comment (michalsmiarowski) [reply src/components/Modal/MapOperatorToStakingProviderSuccessModal/index.tsx]: Fixed in 676058f0e90ae34a6d3350b34261fcc5fb1524be

File: src/components/Modal/MapOperatorToStakingProviderSuccessModal/index.tsx [hunk 31]
```diff
@@ -36,44 +29,51 @@ const MapOperatorToStakingProviderSuccessBase: FC<
...
-                <BodySm>Operator</BodySm>
+                <BodySm>Provider Address</BodySm>
                 <BodySm>
-                  {shortenAddress(transactions[0].application.operator)}
+                  {shortenAddress(transactions[0].application.stakingProvider)}
                 </BodySm>
               </HStack>
             </ListItem>
-            <ListItem key="map_operator_succes_modal__staking_provider">
+            <ListItem key="map_operator_success_modal__operator">
```
[the remark this answers is not in the document]
Comment (michalsmiarowski) [reply src/components/Modal/MapOperatorToStakingProviderSuccessModal/index.tsx]: Fixed in 676058f0e90ae34a6d3350b34261fcc5fb1524be

File: src/store/account/effects.ts (hunk 25 above)
Comment (michalsmiarowski) [reply src/store/account/effects.ts]: Fixed in 009344de756a6593c914dec921f15bdd2ce13b55

File: src/store/account/slice.ts (hunk 26 above)
Comment (michalsmiarowski) [reply src/store/account/slice.ts]: Fixed in c5453fdba5eb88c51259e8c60a66bc010648f832

File: src/store/account/slice.ts (hunk 27 above)
Comment (michalsmiarowski) [reply src/store/account/slice.ts]: Fixed in 2fd71544f69bea87569f98eb62149aa93f710ee2

File: src/store/connected-account/connectedAccountSlice.ts (hunk 17 above)
Comment (michalsmiarowski) [reply src/store/connected-account/connectedAccountSlice.ts]: Fixed in f754bc4f0a0f1f626255c1279d8f7ccdfca703c8 and 390eaea8ac74313b2a48458ab44c8b234971ef15

File: src/store/connected-account/connectedAccountSlice.ts (hunk 18 above)
Comment (michalsmiarowski) [reply src/store/connected-account/connectedAccountSlice.ts]: Fixed in 7cf4736f217ed8dfb9a84c0fdc262a242f064d7d

File: src/store/index.ts (hunk 9 above)
[the remark this answers is not in the document]
Comment (michalsmiarowski) [reply src/store/index.ts]: This does not work for me. Even though the `deactivate` event is emited it is not catched in the `AppBody`'s `useEffect`. It's probably because the events are cleared/removed before the event is fired 🤔

[the remark this answers is not in the document]
Comment (r-czajkowski) [reply src/store/index.ts]: Let's address in a separate PR.

**Review by r-czajkowski — APPROVED** [review]
LGTM! :shipit:

File: src/components/Modal/MapOperatorToStakingProviderConfirmationModal/index.tsx (hunk 1 above)
Comment (michalsmiarowski) [reply src/components/Modal/MapOperatorToStakingProviderConfirmationModal/index.tsx:70]: This will be addressed in https://github.com/threshold-network/token-dashboard/pull/278

**Review by r-czajkowski — APPROVED** [review]
